// Code generated by ogen, DO NOT EDIT.

package api

import (
	"context"

	ht "github.com/ogen-go/ogen/http"
)

// UnimplementedHandler is no-op Handler which returns http.ErrNotImplemented.
type UnimplementedHandler struct{}

var _ Handler = UnimplementedHandler{}

// GetAuthenticationStatus implements getAuthenticationStatus operation.
//
// Delegate the authentication decision to the android device.
//
// GET /auth
func (UnimplementedHandler) GetAuthenticationStatus(ctx context.Context, req *AuthRequest) (r GetAuthenticationStatusRes, _ error) {
	return r, ht.ErrNotImplemented
}

// NewError creates *ErrorResonseStatusCode from error returned by handler.
//
// Used for common default response.
func (UnimplementedHandler) NewError(ctx context.Context, err error) (r *ErrorResonseStatusCode) {
	r = new(ErrorResonseStatusCode)
	return r
}
