# This file was generated by GoReleaser. DO NOT EDIT.
# vim: set ft=nix ts=2 sw=2 sts=2 et sta
{
system ? builtins.currentSystem
, pkgs
, lib
, fetchurl
, installShellFiles
}:
let
  shaMap = {
    i686-linux = "1wlyi9gjicjbl3sj6m2x7d1fs1glh49rayxf2dszv5g54md45ygj";
    x86_64-linux = "04nr0nl3h4dn8w2i2h2yl97p766rc4qlgpq6437ql2k2qd3g9zsv";
    aarch64-linux = "01l0n5ndrhjvidyr8llshypxf2jsmvkrsbn007z2f162wbvs9jhg";
    x86_64-darwin = "1s2q47fwbqqjphki82h3qwxfxar4gzdwcbydi1q9cmqc99vgxaf7";
    aarch64-darwin = "1jg9k3d9sciqkrg5zz13yn73ka9gb1gr4x996z58316a4hv8jsl7";
  };

  urlMap = {
    i686-linux = "https://github.com/gernotfeichter/alp/releases/download/1.1.1/alp_Linux_i386.tar.gz";
    x86_64-linux = "https://github.com/gernotfeichter/alp/releases/download/1.1.1/alp_Linux_x86_64.tar.gz";
    aarch64-linux = "https://github.com/gernotfeichter/alp/releases/download/1.1.1/alp_Linux_arm64.tar.gz";
    x86_64-darwin = "https://github.com/gernotfeichter/alp/releases/download/1.1.1/alp_Darwin_x86_64.tar.gz";
    aarch64-darwin = "https://github.com/gernotfeichter/alp/releases/download/1.1.1/alp_Darwin_arm64.tar.gz";
  };
in
pkgs.stdenv.mkDerivation {
  pname = "alp";
  version = "1.1.1";
  src = fetchurl {
    url = urlMap.${system};
    sha256 = shaMap.${system};
  };

  sourceRoot = ".";

  nativeBuildInputs = [ installShellFiles ];

  installPhase = ''
    mkdir -p $out/bin
    chmod 4755 $binary
    cp -vr $binary $out/bin/$binary
  '';

  system = system;

  meta = {
    description = "alp - android-linux-pam
Alp is a convenient - yet secure (DISCLAIMER: still your risk!) - authentication method that lets you use your android device as a key for your Linux machine.
The idea of alp is, instead of typing a password on the Linux machine, the user only clicks a button on an android device to confirm an authentication/authorisation request.";
    homepage = "https://github.com/gernotfeichter/alp";
    license = lib.licenses.GPLv2;

    platforms = [
      "aarch64-darwin"
      "aarch64-linux"
      "i686-linux"
      "x86_64-darwin"
      "x86_64-linux"
    ];
  };
}
